# Generated by Django 5.0.4 on 2024-04-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Full_name',
        ),
    ]
