# Generated by Django 5.0.4 on 2024-04-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellbook', '0002_remove_profile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Profile', models.ImageField(blank=True, upload_to='Seller_Profile')),
                ('SellerID', models.CharField(max_length=20, unique=True)),
                ('Seller_NID', models.ImageField(blank=True, upload_to='NID_pics')),
                ('address', models.CharField(max_length=100)),
                ('Gmail', models.EmailField(max_length=50)),
                ('city_town', models.CharField(max_length=50)),
                ('postcode_zip', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('Shop_name', models.CharField(max_length=50)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('Sellerusername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
