# Generated by Django 5.0.4 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellbook', '0004_seller_profile_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
