# Generated by Django 5.0.4 on 2024-04-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellbook', '0004_seller_profile_additional_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.ImageField(blank=True, upload_to='book_covers')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellbook.seller_profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.category')),
            ],
        ),
    ]
