# Generated by Django 5.0.4 on 2024-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_ID',
            field=models.CharField(default=1, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
