# Generated by Django 5.0.4 on 2024-04-23 05:52

import Eshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0002_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_ID',
            field=models.CharField(default=Eshop.models.generate_book_id, max_length=4, unique=True),
        ),
    ]
