# Generated by Django 5.0.4 on 2024-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_alter_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='none', max_length=4),
        ),
    ]
