# Generated by Django 5.0.4 on 2024-04-25 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_remove_book_category_book_categories'),
        ('Sellbook', '0004_seller_profile_additional_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellbook.profile')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellbook.seller_profile')),
            ],
        ),
    ]
