# Generated by Django 5.0.4 on 2024-04-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0009_membership'),
        ('Sellbook', '0004_seller_profile_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sellbook.profile'),
            preserve_default=False,
        ),
    ]
