# Generated by Django 5.0.4 on 2024-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0010_membership_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
