# Generated by Django 5.0.4 on 2024-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newbookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('writter_name', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('book_image', models.ImageField(default='None', upload_to='book_images/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
